# Generated by Django 6.0.3 on 2026-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('month', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2026)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_data', models.JSONField(blank=True, default=dict, null=True)),
                ('month', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2026)),
            ],
        ),
    ]
