# Generated by Django 6.0.3 on 2026-04-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_branch_dynamic_data_alter_dynamiccolumn_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='dynamic_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dynamiccolumn',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dynamic_data',
            field=models.JSONField(default=dict),
        ),
    ]
