# Generated by Django 6.0.3 on 2026-04-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_branchcolumn_alter_branch_dynamic_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
