# Generated by Django 6.0.3 on 2026-04-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_compliancetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
